### ISSUE TITLE
バックエンドが遅い

### ISSUE THREAD

**Issue by yu-stripe** [yu-stripe/3ds-workshop#18]

**Comment by hideokamoto-stripe** [comment]
速度優先なら、AWS LambdaとかCloudflare Workersあたりの方が良いかなぁとは思います。
おそらくコンテナを起動させてからRubyを実行するような仕組みになっているはずなんで
@yu-stripe

**Comment by yu-stripe** [comment]
しっかり見ると、stripeからのレスポンスだったので、どうしようもなさそう。
